### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [bennorth/git-dendrify#2]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary gitdendrify -w /tmp/ext gitdendrify==0.2.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting gitdendrify==0.2.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/26a/e8dc8d2706c4e/gitdendrify-0.2.0.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-fbax_91m/gitdendrify/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-fbax_91m/gitdendrify/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-fbax_91m/gitdendrify/pip-egg-info
         cwd: /tmp/pip-wheel-fbax_91m/gitdendrify/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-fbax_91m/gitdendrify/setup.py", line 8, in <module>
        with open('long-description.md', 'rt') as f_in:
    FileNotFoundError: [Errno 2] No such file or directory: 'long-description.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by bennorth** [comment]
Thanks for the report and fix, which I've included in `develop`.  See your #3 for details.
